Repository Project-AETHA/aetha-backend, pull requests merged in 2024-11, with the labels that each got.

#32 statService
  src/main/java/com/nighthawk/aetha_backend/entity/AuthUser.java
  src/main/java/com/nighthawk/aetha_backend/entity/Poem.java
  src/main/java/com/nighthawk/aetha_backend/repository/AuthUserRepository.java
  src/main/java/com/nighthawk/aetha_backend/service/StatService.java
Labels: improvement

#34 Reported Content
  logs/aetha_backend.log
  src/main/java/com/nighthawk/aetha_backend/controller/ReportedContentController.java
  src/main/java/com/nighthawk/aetha_backend/dto/ReportedContentDTO.java
  src/main/java/com/nighthawk/aetha_backend/dto/StatDTO.java
  src/main/java/com/nighthawk/aetha_backend/entity/ReportedContent.java
  src/main/java/com/nighthawk/aetha_backend/repository/ReportedContentRepository.java
  src/main/java/com/nighthawk/aetha_backend/service/ReportedContentService.java
  src/main/java/com/nighthawk/aetha_backend/utils/predefined/ContentType.java
Labels: feature, improvement

#36 Feature/reported content
  src/main/java/com/nighthawk/aetha_backend/controller/ReportedContentController.java
  src/main/java/com/nighthawk/aetha_backend/dto/NovelReportedContentSummaryDTO.java
  src/main/java/com/nighthawk/aetha_backend/dto/PoemDTO.java
  src/main/java/com/nighthawk/aetha_backend/dto/PoemReportedContentSummaryDTO.java
  src/main/java/com/nighthawk/aetha_backend/dto/ReportedContentDTO.java
  src/main/java/com/nighthawk/aetha_backend/dto/ReportedNovelDTO.java
  src/main/java/com/nighthawk/aetha_backend/dto/ReportedPoemDTO.java
  src/main/java/com/nighthawk/aetha_backend/entity/NovelReportedContent.java
  src/main/java/com/nighthawk/aetha_backend/entity/PoemReportedContent.java
  src/main/java/com/nighthawk/aetha_backend/repository/NovelReportedContentRepository.java
  src/main/java/com/nighthawk/aetha_backend/repository/PoemReportedContentRepository.java
  src/main/java/com/nighthawk/aetha_backend/repository/ReportedContentRepository.java
  src/main/java/com/nighthawk/aetha_backend/service/ReportedContentService.java
  src/main/java/com/nighthawk/aetha_backend/utils/predefined/ContentType.java
Labels: feature

#37 Feature/profile-settings
  pom.xml
  src/main/java/com/nighthawk/aetha_backend/controller/MessageController.java
  src/main/java/com/nighthawk/aetha_backend/controller/NotificationSettingsController.java
  src/main/java/com/nighthawk/aetha_backend/controller/SettingsController.java
  src/main/java/com/nighthawk/aetha_backend/dto/MessageDTO.java
  src/main/java/com/nighthawk/aetha_backend/dto/NotificationSettingsDTO.java
  src/main/java/com/nighthawk/aetha_backend/dto/SettingsDTO.java
  src/main/java/com/nighthawk/aetha_backend/entity/Message.java
  src/main/java/com/nighthawk/aetha_backend/entity/MessageStatus.java
  src/main/java/com/nighthawk/aetha_backend/entity/NotificationSettings.java
  src/main/java/com/nighthawk/aetha_backend/entity/Settings.java
  src/main/java/com/nighthawk/aetha_backend/repository/MessageRepository.java
  src/main/java/com/nighthawk/aetha_backend/repository/NotificationSettingsRepository.java
  src/main/java/com/nighthawk/aetha_backend/repository/SettingsRepository.java
  src/main/java/com/nighthawk/aetha_backend/service/MessageService.java
  src/main/java/com/nighthawk/aetha_backend/service/NotificationSettingsService.java
  src/main/java/com/nighthawk/aetha_backend/service/SettingsService.java
Labels: feature, improvement

#38 User followings and followers
  src/main/java/com/nighthawk/aetha_backend/controller/EbookExternalController.java
  src/main/java/com/nighthawk/aetha_backend/controller/FollowUserController.java
  src/main/java/com/nighthawk/aetha_backend/dto/NotificationDTO.java
  src/main/java/com/nighthawk/aetha_backend/dto/RequestDTO.java
  src/main/java/com/nighthawk/aetha_backend/entity/FollowUser.java
  src/main/java/com/nighthawk/aetha_backend/repository/FollowUserRepository.java
  src/main/java/com/nighthawk/aetha_backend/service/EbookExternalService.java
  src/main/java/com/nighthawk/aetha_backend/service/FollowUserService.java
Labels: enhancement

#39 completed reported content
  src/main/java/com/nighthawk/aetha_backend/controller/ReportedContentController.java
  src/main/java/com/nighthawk/aetha_backend/dto/NovelReportedContentSummaryDTO.java
  src/main/java/com/nighthawk/aetha_backend/dto/PoemReportedContentSummaryDTO.java
  src/main/java/com/nighthawk/aetha_backend/dto/ReportedNovelDTO.java
  src/main/java/com/nighthawk/aetha_backend/entity/NovelReportedContent.java
  src/main/java/com/nighthawk/aetha_backend/entity/PoemReportedContent.java
  src/main/java/com/nighthawk/aetha_backend/repository/NovelReportedContentRepository.java
  src/main/java/com/nighthawk/aetha_backend/repository/PoemReportedContentRepository.java
  src/main/java/com/nighthawk/aetha_backend/service/ReportedContentService.java
Labels: enhancement

#40 Subscription and Subscription Tiers
  src/main/java/com/nighthawk/aetha_backend/controller/SubscriptionController.java
  src/main/java/com/nighthawk/aetha_backend/dto/SubscriptionDTO.java
  src/main/java/com/nighthawk/aetha_backend/entity/Subscription.java
  src/main/java/com/nighthawk/aetha_backend/entity/SubscriptionTiers.java
  src/main/java/com/nighthawk/aetha_backend/repository/SubscriptionRepository.java
  src/main/java/com/nighthawk/aetha_backend/repository/SubscriptionTiersRepository.java
  src/main/java/com/nighthawk/aetha_backend/service/SubscriptionService.java
  src/main/java/com/nighthawk/aetha_backend/service/SubscriptionTiersService.java
  src/main/java/com/nighthawk/aetha_backend/utils/predefined/SubscriptionStatus.java
Labels: feature

#41 Feature/profile settings
  src/main/java/com/nighthawk/aetha_backend/controller/ProfileDetailsController.java
  src/main/java/com/nighthawk/aetha_backend/controller/ProfileReviewController.java
  src/main/java/com/nighthawk/aetha_backend/entity/ProfileDetails.java
  src/main/java/com/nighthawk/aetha_backend/entity/ProfileReview.java
  src/main/java/com/nighthawk/aetha_backend/repository/ProfileDetailsRepository.java
  src/main/java/com/nighthawk/aetha_backend/repository/ProfileReviewRepository.java
  src/main/java/com/nighthawk/aetha_backend/service/ProfileDetailsService.java
  src/main/java/com/nighthawk/aetha_backend/service/ProfileReviewService.java
Labels: enhancement

#43 Short stories - In Progress
  src/main/java/com/nighthawk/aetha_backend/controller/ShortStoryController.java
  src/main/java/com/nighthawk/aetha_backend/dto/ShortStoryDTO.java
  src/main/java/com/nighthawk/aetha_backend/entity/ShortStory.java
  src/main/java/com/nighthawk/aetha_backend/entity/Tags2.java
  src/main/java/com/nighthawk/aetha_backend/repository/ShortStoryRepository.java
  src/main/java/com/nighthawk/aetha_backend/service/ShortStoryService.java
  src/main/java/com/nighthawk/aetha_backend/utils/predefined/ContentWarnings.java
Labels: enhancement

#47 Feature/comments
  Dockerfile
  src/main/java/com/nighthawk/aetha_backend/controller/CommentController.java
  src/main/java/com/nighthawk/aetha_backend/controller/RatingController.java
  src/main/java/com/nighthawk/aetha_backend/dto/CommentDTO.java
  src/main/java/com/nighthawk/aetha_backend/entity/Comment.java
  src/main/java/com/nighthawk/aetha_backend/repository/CommentRepository.java
  src/main/java/com/nighthawk/aetha_backend/repository/RatingRepository.java
  src/main/java/com/nighthawk/aetha_backend/service/CommentService.java
  src/main/java/com/nighthawk/aetha_backend/service/RatingService.java
Labels: enhancement
